# Generated by Django 4.1.6 on 2024-03-22 10:59

from django.db import migrations, models
import django.db.models.deletion
import onboarding.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sensor_type', models.CharField(choices=[('SCK-AQ', 'Smart Citizen Kit Air Quality'), ('WU-PWS', 'BRESSER WIFI ClearView Weather Station with 7-in-1 Sensor')], max_length=10)),
                ('location', models.JSONField()),
                ('properties', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstallationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=onboarding.models.sensor_directory_path)),
                ('video', models.FileField(blank=True, null=True, upload_to=onboarding.models.sensor_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.sensorthing')),
            ],
            options={
                'ordering': ['sensor', 'step_number'],
                'unique_together': {('sensor', 'step_number')},
            },
        ),
    ]
