# Generated by Django 4.1.6 on 2024-03-22 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('SCK-AQ', 'Smart Citizen Kit Air Quality'), ('WU-PWS', 'BRESSER WIFI ClearView Weather Station with 7-in-1 Sensor')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensorthing',
            name='sensor_type',
        ),
        migrations.AddField(
            model_name='sensorthing',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onboarding.sensor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installationstep',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.sensor'),
        ),
    ]
