# Generated by Django 4.1.6 on 2024-03-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_sensor_remove_sensorthing_sensor_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationstep',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
