# Generated by Django 4.1.6 on 2024-03-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_alter_installationstep_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationstep',
            name='input_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='installationstep',
            name='input_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='installationstep',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='URL or path to redirect after the step is completed', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='installationstep',
            name='step_type',
            field=models.CharField(choices=[('media', 'Media Presentation'), ('input', 'Input Gathering')], default='media', max_length=5),
        ),
    ]
