# Generated by Django 4.1.6 on 2024-04-16 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_alter_sensor_project_year'),
        ('onboarding', '0006_installationstep_description_en_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationstep',
            name='sensor',
            field=models.ForeignKey(default=60, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalogue.sensor'),
        ),
        migrations.AlterField(
            model_name='sensorthing',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.sensor'),
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
