# Generated by Django 4.1.6 on 2024-04-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_alter_installationstep_sensor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorthing',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
