# Generated by Django 4.1.6 on 2024-04-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_alter_sensorthing_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationstep',
            name='description_ca',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installationstep',
            name='description_eu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installationstep',
            name='description_pl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installationstep',
            name='description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installationstep',
            name='title_ca',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='installationstep',
            name='title_eu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='installationstep',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='installationstep',
            name='title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
