# Generated by Django 4.1.6 on 2023-02-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="sensor_pictures/"
            ),
        ),
    ]
