# Generated by Django 4.1.6 on 2023-04-08 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deploymentcost',
            options={'verbose_name': 'Deployment Cost', 'verbose_name_plural': 'Deployment Costs'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-ordered_date'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='sensors',
        ),
        migrations.RemoveField(
            model_name='ordersensor',
            name='ordered',
        ),
        migrations.AddField(
            model_name='ordersensor',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='catalogue.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersensor',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
