# Generated by Django 4.1.6 on 2023-03-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_alter_hazard_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, verbose_name="Cost(€)"
            ),
        ),
    ]
