# Generated by Django 4.1.6 on 2023-02-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_alter_sensor_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="minimum_purchase_quantity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Minimum purchase quantity"
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="spatial_density_distribution",
            field=models.TextField(
                blank=True,
                default="Not provided",
                null=True,
                verbose_name="Spatial Density / min number and distribution description",
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="spatial_density_per_area",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Spatial Density / min number per area [km2]",
            ),
        ),
    ]
