# Generated by Django 4.1.6 on 2023-04-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_deploymentcost_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersensor',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordersensor',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='ordersensor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderSensor',
        ),
    ]
