# Generated by Django 4.1.6 on 2023-02-27 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_remove_sensor_hazard"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="hazard",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensor",
                to="catalogue.hazard",
            ),
            preserve_default=False,
        ),
    ]
