# Generated by Django 4.1.6 on 2023-03-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_alter_sensor_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assemblyoperation",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VD", "Very difficult"),
                    ("DI", "Difficult"),
                    ("NE", "Neutral"),
                    ("EA", "Easy"),
                    ("VE", "Very easy"),
                ],
                default=None,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="citizenscienceoperation",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VD", "Very difficult"),
                    ("DI", "Difficult"),
                    ("NE", "Neutral"),
                    ("EA", "Easy"),
                    ("VE", "Very easy"),
                ],
                default=None,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="dataanalysisoperation",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VD", "Very difficult"),
                    ("DI", "Difficult"),
                    ("NE", "Neutral"),
                    ("EA", "Easy"),
                    ("VE", "Very easy"),
                ],
                default=None,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="installationoperation",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VD", "Very difficult"),
                    ("DI", "Difficult"),
                    ("NE", "Neutral"),
                    ("EA", "Easy"),
                    ("VE", "Very easy"),
                ],
                default=None,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseoperation",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VD", "Very difficult"),
                    ("DI", "Difficult"),
                    ("NE", "Neutral"),
                    ("EA", "Easy"),
                    ("VE", "Very easy"),
                ],
                default=None,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="installation_costs",
            field=models.CharField(
                blank=True,
                choices=[("H", "High"), ("M", "Medium"), ("L", "Low")],
                default=None,
                max_length=1,
                verbose_name="Installation Cost",
            ),
        ),
    ]
