# Generated by Django 4.1.6 on 2023-02-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_sensor_hazard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hazard",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
