# Generated by Django 4.1.6 on 2023-02-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_alter_sensor_data_refresh_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensor",
            old_name="sensor_slug",
            new_name="slug",
        ),
    ]
