# Generated by Django 4.1.6 on 2023-02-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_alter_hazard_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="id_old",
            field=models.CharField(max_length=20, verbose_name="Sensor Old ID"),
        ),
    ]
