# Generated by Django 4.1.6 on 2023-03-09 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_alter_assemblyoperation_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="assembly_operation",
            field=models.ForeignKey(
                blank=True,
                default=None,
                max_length=2,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.assemblyoperation",
                verbose_name="Assembly Operations Complexity",
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="citizen_science_operation",
            field=models.ForeignKey(
                blank=True,
                default=None,
                max_length=2,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.citizenscienceoperation",
                verbose_name="Citizen Science Activities Complexity",
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="data_analysis_operation",
            field=models.ForeignKey(
                blank=True,
                default=None,
                max_length=2,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.dataanalysisoperation",
                verbose_name="Data Analysis Operations Complexity",
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="installation_costs",
            field=models.CharField(
                blank=True,
                choices=[("H", "High"), ("M", "Medium"), ("L", "Low")],
                default=None,
                max_length=1,
                null=True,
                verbose_name="Installation Cost",
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="installation_operation",
            field=models.ForeignKey(
                blank=True,
                default=None,
                max_length=2,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.installationoperation",
                verbose_name="Installation Operation Complexity ",
            ),
        ),
    ]
