# Generated by Django 4.1.6 on 2023-02-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0006_rename_orderedsensor_ordersensor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="minimum_purchase_quantity",
            field=models.IntegerField(
                blank=True,
                default=1,
                null=True,
                verbose_name="Minimum purchase quantity",
            ),
        ),
    ]
