# Generated by Django 4.1.6 on 2023-02-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0007_alter_sensor_minimum_purchase_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="hazard",
            field=models.CharField(
                choices=[
                    ("SL", "Sea level rise"),
                    ("CF", "Coastal flooding"),
                    ("LF", "Land and river flooding"),
                    ("CE", "Coastal Erosion"),
                    ("SS", "Storm Surge"),
                    ("DH", "Droughts and heat waves"),
                    ("LS", "Landslide"),
                ],
                default=1,
                max_length=2,
                verbose_name="Hazard",
            ),
            preserve_default=False,
        ),
    ]
