# Generated by Django 4.1.6 on 2023-02-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0008_sensor_hazard"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordersensor",
            options={
                "verbose_name": "Order Sensor",
                "verbose_name_plural": "Order Sensors",
            },
        ),
    ]
