# Generated by Django 4.1.6 on 2023-04-17 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_assemblyoperation_slug_citizenscienceoperation_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersensor',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='ordersensor',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='installationcost',
            options={'verbose_name': 'Deployment Cost', 'verbose_name_plural': 'Deployment Costs'},
        ),
        migrations.AlterModelOptions(
            name='installationoperation',
            options={'verbose_name': 'Deployment Operation Complexity', 'verbose_name_plural': 'Deployment Operation Complexities'},
        ),
        migrations.AddField(
            model_name='sensor',
            name='assembly_operation_public_involvement',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Public Involvement & Assembly Operations'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='data_analysis_public_involvement',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Public Involvement & Data Analysis Operations'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='deployment_operation_public_involvement',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Public Involvement & Deployment Operations'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hazards_image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='accuracy',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Accuracy (error of the measurements)'),
        ),

        migrations.AlterField(
            model_name='sensor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sensor_images/%Y/%m/%d'),
        ),

        migrations.AlterField(
            model_name='sensor',
            name='installation_operation',
            field=models.ForeignKey(blank=True, default=None, max_length=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.installationoperation', verbose_name='Deployment operation Complexity'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='project_name',
            field=models.CharField(blank=True, default=None, max_length=250, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='project_website',
            field=models.URLField(blank=True, null=True, verbose_name='Project Website'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='reference_partner',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='Reference partner'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Unit of Measurement'),
        ),
        migrations.AlterField(
            model_name='sensorimage',
            name='images',
            field=models.ImageField(blank=True, upload_to='sensor_images/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderSensor',
        ),
    ]
