# Generated by Django 4.1.6 on 2023-03-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_assemblyoperation_slug_citizenscienceoperation_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='accuracy',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sensor Accuracy'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Cost(€)'),
        ),
    ]
