# Generated by Django 4.1.6 on 2023-03-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_alter_sensor_accuracy_alter_sensor_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
