# Generated by Django 4.1.6 on 2023-04-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_remove_ordersensor_sensor_remove_ordersensor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='id_old',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sensor Old ID'),
        ),
    ]
