# Generated by Django 4.1.6 on 2023-02-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0010_alter_ordersensor_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Cost(€)"
            ),
        ),
    ]
