# Generated by Django 4.1.6 on 2023-04-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_alter_sensor_id_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='assembly_operation_public_involvement',
            field=models.TextField(blank=True, null=True, verbose_name='Public Involvement & Assembly Operations'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='data_analysis_public_involvement',
            field=models.TextField(blank=True, null=True, verbose_name='Public Involvement & Data Analysis Operations'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='deployment_operation_public_involvement',
            field=models.TextField(blank=True, null=True, verbose_name='Public Involvement & Deployment Operations'),
        ),
    ]
