# Generated by Django 4.1.6 on 2023-02-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0011_alter_sensor_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="sensor_pictures/%Y/%m/%d"
            ),
        ),
    ]
