# Generated by Django 4.1.6 on 2023-04-18 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_alter_sensor_assembly_operation_public_involvement_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstallationCost',
            new_name='DeploymentCost',
        ),
        migrations.RenameModel(
            old_name='InstallationOperation',
            new_name='DeploymentOperation',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='installation_operation',
            new_name='deployment_operation',
        ),
    ]
