# Generated by Django 4.1.6 on 2023-03-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_remove_sensor_installation_costs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='accuracy',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Accuracy (error of the measurements)'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Unit of Measurement'),
        ),
    ]
