# Generated by Django 4.1.6 on 2023-02-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0012_alter_sensor_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensor",
            old_name="picture",
            new_name="image",
        ),
    ]
