# Generated by Django 4.1.6 on 2023-03-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_alter_sensor_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='id_old',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sensor Old ID'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='reference_partner',
            field=models.CharField(blank=True, max_length=150, verbose_name='Reference partner'),
        ),
    ]
