# Generated by Django 4.1.6 on 2023-04-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_assemblyoperation_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentcost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deployment/%Y/%m/%d'),
        ),
    ]
