# Generated by Django 4.1.6 on 2023-04-22 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_deploymentcost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploymentcost',
            name='name',
        ),
    ]
