# Generated by Django 4.1.6 on 2023-04-22 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_remove_deploymentcost_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploymentcost',
            name='image',
        ),
        migrations.AddField(
            model_name='deploymentcost',
            name='name',
            field=models.CharField(blank=True, choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='deployment_costs',
            field=models.ForeignKey(blank=True, default=None, max_length=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.deploymentcost', verbose_name='Deployment Cost'),
        ),
    ]
