# Generated by Django 4.1.6 on 2023-05-19 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_deploymentcost_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=250, null=True)),
                ('response', models.TextField(blank=True)),
                ('sensor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalogue.sensor')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
    ]
