# Generated by Django 4.1.6 on 2023-09-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_alter_sensor_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='mobile_data_connection',
            field=models.BooleanField(default=False, verbose_name='4G Connection'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='relevant_to_ewss',
            field=models.BooleanField(default=False, verbose_name='Relevant to the EWSS'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='relevant_to_models',
            field=models.BooleanField(default=False, verbose_name='Relevant to WP3 Models'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tested_with_score',
            field=models.BooleanField(default=False, verbose_name='Tested with SCORE'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='wifi_connection',
            field=models.BooleanField(default=False, verbose_name='Wi-Fi Connection'),
        ),
    ]
