# Generated by Django 4.1.6 on 2023-09-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_alter_sensor_mobile_data_connection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost(€)'),
        ),
    ]
